---
version: '3.8'
services:
  db:
    image: tineshdocker/py-jen1:db
    ports:
      - "0101:3306"
    deploy:
      replicas: 1
    networks:
      - gcp10

  auth_service:
    image: tineshdocker/py-jen1:auth
    ports:
      - "0202:5001"
    deploy:
      replicas: 1
    networks:
      - gcp10 

  book_service:
    image: tineshdocker/py-jen1:book
    ports:
      - "0303:5002"
    deploy:
      replicas: 1
    networks:
      - gcp10

  borrow_service:
    image: tineshdocker/py-jen1:borrow
    ports:
      - "0404:5003"
    deploy:
      replicas: 1
    networks:
      - gcp10

  frontend:
    image: tineshdocker/py-jen1:frontend
    ports:
      - "0505:5000"
    deploy:
      replicas: 1
    networks:
      - gcp10


networks:
       gcp10:
