---
version: "3.8"
services:
  db:
    image: tineshdocker/db
    ports:
      - "5678:3306"
    deploy:
      replicas: 1
    networks:
      - project
    
  auth_service:
    image: tineshdocker/auth
    ports:
      - "9876:5001"
    deploy:
      replicas: 1
    networks:
      - project
   
  book_service:
    image: tineshdocker/book
    ports:
      - "8765:5002"
    deploy:
      replicas: 1
    networks:
      - project

  borrow_service:
    image: tineshdocker/borrow
    ports:
      - "7654:5003"
    deploy:
      replicas: 1
    networks:
      - project

  frontend:
    image: tineshdocker/frontend
    ports:
      - "6543:5000"
    deploy:
      replicas: 1
    networks:
      - project

networks:
  project:
