---
version: '3.8'
services:
  db:
    image: tineshdocker/db
    ports:
      - "9999:3306"
    deploy:
      replicas: 1
    networks:
      - gcp7

  auth_service:
    image: tineshdocker/auth
    ports:
      - "8888:5001"
    deploy:
      replicas: 1
    networks:
      - gcp7 

  book_service:
    image: tineshdocker/book
    ports:
      - "7777:5002"
    deploy:
      replicas: 1
    networks:
      - gcp7

  borrow_service:
    image: tineshdocker/borrow
    ports:
      - "6666:5003"
    deploy:
      replicas: 1
    networks:
      - gcp7

  frontend:
    image: tineshdocker/frontend
    ports:
      - "5555:5000"
    deploy:
      replicas: 1
    networks:
      - gcp7


networks:
       gcp7:
