---
version: '3.8'
services:
  db:
    image: tineshdocker/py-jen1:db
    ports:
      - "9999:3306"
    deploy:
      replicas: 1
    networks:
      - gcp9

  auth_service:
    image: tineshdocker/py-jen1:auth
    ports:
      - "8888:5001"
    deploy:
      replicas: 1
    networks:
      - gcp9 

  book_service:
    image: tineshdocker/py-jen1:book
    ports:
      - "9999:5002"
    deploy:
      replicas: 1
    networks:
      - gcp9

  borrow_service:
    image: tineshdocker/py-jen1:borrow
    ports:
      - "6666:5003"
    deploy:
      replicas: 1
    networks:
      - gcp9

  frontend:
    image: tineshdocker/py-jen1:frontend
    ports:
      - "5555:5000"
    deploy:
      replicas: 1
    networks:
      - gcp9


networks:
       gcp9:
